# Site settings

url: "sohogreen.com"
title: "Soho Green"
author: "Samson Danziger"
author-github: "marscapone"
description: "Basic website for Soho Green Charity"
keywords: "soho, green, sohogreen, central london, parks, wall of light"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: ""
disqus-shortname:

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  'Wall of Light': 'wall-of-light'
  'The Art Loo': 'the-art-loo'
  'The Table': 'the-table'
  Transformations: 'transformations'
  Contact: 'contact'

collections:
  - wall_photos
  - loo_photos
  - table_photos
  - transform_photos

background-img: "/img/intro-bg.jpg"

# About variables

me-img:
contact-email:

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: True

# Career variables

events:
  #  - image: "/img/career/microsoft.jpg"
  #  date: "September 2014 - Today"
  #  description: "Software Engineer @ Microsoft Development Center Norway, working @ the <a href=\"http://dev.office.com/officegraph\" target=\"_blank\"> Office Graph</a>"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "github"
    url: "https://github.com/sohogreen"
  - title: "linkedin"
    url: ""
  - title: "youtube"
    url: ""
  - title: "facebook"
    url: "https://www.facebook.com/sohogreen"
  - title: "twitter"
    url: "https://twitter.com/sohogreen"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", "README.md"]
